import type {
  CommunityEvent,
  EducationProgram,
  EmergencyResource,
  GovernmentScheme,
  HealthFacility,
  MobilityAsset,
  PlatformUser,
  TransparencyProject,
  UtilityRequestType,
  Ward,
  WasteDropPoint,
} from './types.js';

export const SEED_WARDS: Ward[] = [
  { id: 'ward-1', name: 'Ward 1 — Civil Lines', ulbName: 'Demo Municipal Corp', lat: 28.6139, lng: 77.209 },
  { id: 'ward-2', name: 'Ward 2 — Karol Bagh', ulbName: 'Demo Municipal Corp', lat: 28.6519, lng: 77.1909 },
  { id: 'ward-3', name: 'Ward 3 — Saket', ulbName: 'Demo Municipal Corp', lat: 28.5244, lng: 77.2066 },
];

export const SEED_USERS: PlatformUser[] = [
  {
    id: 'user-citizen-1',
    name: 'Demo Citizen',
    phone: '9999999999',
    role: 'citizen',
    wardId: 'ward-1',
    preferredLanguage: 'en',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user-official-1',
    name: 'Demo Official',
    phone: '8888888888',
    role: 'official',
    wardId: 'ward-1',
    preferredLanguage: 'en',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user-field-1',
    name: 'Field Executive',
    phone: '7777777777',
    role: 'field_staff',
    wardId: 'ward-2',
    preferredLanguage: 'hi',
    createdAt: new Date().toISOString(),
  },
];

export const SEED_SCHEMES: GovernmentScheme[] = [
  {
    id: 'scheme-pm-kisan',
    name: 'PM-KISAN',
    level: 'central',
    department: 'Agriculture',
    summary: 'Income support for eligible farmer families.',
    benefits: ['₹6,000 per year in three installments'],
    documents: ['Aadhaar', 'Land records or farmer registration'],
    applyUrl: 'https://pmkisan.gov.in/',
    helpline: '155261',
    tags: ['farmer', 'income'],
    active: true,
    rules: [
      { field: 'annualIncomeInr', operator: 'lte', value: 500000, label: 'Small/marginal farmer household' },
    ],
  },
  {
    id: 'scheme-ayushman',
    name: 'Ayushman Bharat — PM-JAY',
    level: 'central',
    department: 'Health',
    summary: 'Health cover up to ₹5 lakh per family per year for secondary/tertiary care.',
    benefits: ['Cashless treatment at empanelled hospitals'],
    documents: ['Aadhaar', 'Ration card or SECC data'],
    applyUrl: 'https://pmjay.gov.in/',
    helpline: '14555',
    tags: ['health', 'insurance'],
    active: true,
    rules: [
      { field: 'annualIncomeInr', operator: 'lte', value: 500000, label: 'Eligible as per SECC/EWS criteria' },
    ],
  },
  {
    id: 'scheme-girls-scholarship',
    name: 'State Girls Scholarship (Demo)',
    level: 'state',
    department: 'Education',
    summary: 'Scholarship for girl students in classes 9–12.',
    benefits: ['₹3,000 per year tuition support'],
    documents: ['School ID', 'Income certificate'],
    tags: ['education', 'girls'],
    active: true,
    rules: [
      { field: 'gender', operator: 'eq', value: 'female', label: 'Applicant must be female' },
      { field: 'isStudent', operator: 'eq', value: true, label: 'Must be enrolled in school' },
      { field: 'age', operator: 'gte', value: 13, label: 'Minimum age 13' },
      { field: 'age', operator: 'lte', value: 18, label: 'Maximum age 18' },
    ],
  },
  {
    id: 'scheme-senior-pension',
    name: 'Indira Gandhi Old Age Pension (Demo)',
    level: 'central',
    department: 'Social Justice',
    summary: 'Monthly pension for elderly below poverty line.',
    benefits: ['₹200–500 monthly pension (state top-up may apply)'],
    documents: ['Aadhaar', 'Age proof', 'BPL card'],
    tags: ['senior', 'pension'],
    active: true,
    rules: [
      { field: 'age', operator: 'gte', value: 60, label: 'Age 60 or above' },
      { field: 'annualIncomeInr', operator: 'lte', value: 120000, label: 'BPL income threshold' },
    ],
  },
  {
    id: 'scheme-disability',
    name: 'Disability Allowance (Demo Local)',
    level: 'local',
    department: 'Social Welfare — ULB',
    summary: 'Local allowance and assistive device support.',
    benefits: ['Monthly allowance', 'Assistive device camp referral'],
    documents: ['Disability certificate', 'Aadhaar', 'Residence proof'],
    helpline: '1800-000-000',
    tags: ['disability', 'local'],
    active: true,
    rules: [{ field: 'isDisabled', operator: 'eq', value: true, label: 'Valid disability certificate required' }],
  },
];

export const SEED_HEALTH: HealthFacility[] = [
  {
    id: 'hf-1',
    name: 'PHC Civil Lines',
    type: 'phc',
    wardId: 'ward-1',
    lat: 28.6145,
    lng: 77.21,
    hours: 'Mon–Sat 8:00–16:00',
    services: ['OPD', 'Immunization', 'Ayushman desk'],
    phone: '011-23456701',
  },
  {
    id: 'hf-2',
    name: 'CHC Karol Bagh',
    type: 'chc',
    wardId: 'ward-2',
    lat: 28.6525,
    lng: 77.1915,
    hours: '24×7 emergency',
    services: ['Emergency', 'Maternity', 'Lab'],
    phone: '011-23456702',
  },
  {
    id: 'hf-3',
    name: 'City Blood Bank',
    type: 'blood_bank',
    wardId: 'ward-3',
    lat: 28.525,
    lng: 77.207,
    hours: 'Daily 9:00–17:00',
    services: ['Whole blood', 'Platelets'],
    phone: '011-23456703',
  },
];

export const SEED_EDUCATION: EducationProgram[] = [
  {
    id: 'edu-1',
    title: 'Municipal Skill Center — Electrician Batch',
    type: 'skill',
    wardId: 'ward-2',
    summary: '3-month certified electrician training with placement support.',
    eligibility: 'Age 18–35, minimum 10th pass',
    applyUrl: 'https://example.org/skill-electrician',
    startsAt: '2026-10-01',
  },
  {
    id: 'edu-2',
    title: 'Merit Scholarship Portal Registration',
    type: 'scholarship',
    wardId: 'ward-1',
    summary: 'State portal open for UG merit scholarships.',
    eligibility: 'Family income below ₹2.5L, 75%+ marks',
    applyUrl: 'https://example.org/scholarship',
    startsAt: '2026-09-01',
  },
  {
    id: 'edu-3',
    title: 'Ward Library — Extended Hours',
    type: 'library',
    wardId: 'ward-3',
    summary: 'Saket community library open till 21:00 on weekdays.',
    eligibility: 'Free membership with local ID',
  },
];

export const SEED_MOBILITY: MobilityAsset[] = [
  {
    id: 'mob-1',
    name: 'EV Hub — Connaught Place',
    type: 'ev_charging',
    lat: 28.6315,
    lng: 77.2167,
    status: 'available',
    meta: '4 fast chargers',
  },
  {
    id: 'mob-2',
    name: 'Multi-level Parking — Karol Bagh',
    type: 'parking',
    lat: 28.651,
    lng: 77.192,
    status: 'limited',
    meta: '12 slots free',
  },
  {
    id: 'mob-3',
    name: 'Bus Stop — Saket District Centre',
    type: 'bus_stop',
    lat: 28.524,
    lng: 77.206,
    status: 'available',
    meta: 'Route 534, 521',
  },
];

export const SEED_EMERGENCY: EmergencyResource[] = [
  { id: 'em-1', name: 'National Emergency', type: 'helpline', phone: '112', notes: 'All emergencies' },
  { id: 'em-2', name: 'Police', type: 'police', phone: '100', lat: 28.614, lng: 77.209 },
  { id: 'em-3', name: 'Fire', type: 'fire', phone: '101' },
  { id: 'em-4', name: 'Ambulance', type: 'hospital', phone: '108' },
  {
    id: 'em-5',
    name: 'Monsoon Relief Shelter — Ward 1',
    type: 'shelter',
    lat: 28.615,
    lng: 77.208,
    phone: '011-23456999',
    notes: 'Open during orange alert and above',
  },
];

export const SEED_UTILITY_TYPES: UtilityRequestType[] = [
  { id: 'ut-water', name: 'Water supply disruption', department: 'Water Works', slaHours: 24 },
  { id: 'ut-sewer', name: 'Sewer blockage', department: 'Sanitation Engineering', slaHours: 48 },
  { id: 'ut-air', name: 'Air/noise pollution complaint', department: 'Environment', slaHours: 72 },
  { id: 'ut-tanker', name: 'Water tanker request', department: 'Water Works', slaHours: 12 },
];

export const SEED_COMMUNITY: CommunityEvent[] = [
  {
    id: 'ce-1',
    title: 'Lake Cleanup — Saket',
    type: 'drive',
    wardId: 'ward-3',
    lat: 28.523,
    lng: 77.205,
    startsAt: '2026-09-20T07:00:00+05:30',
    slots: 50,
    enrolled: 12,
  },
  {
    id: 'ce-2',
    title: 'Ward Sabha — Civil Lines',
    type: 'ward_meeting',
    wardId: 'ward-1',
    lat: 28.614,
    lng: 77.209,
    startsAt: '2026-09-25T18:00:00+05:30',
  },
  {
    id: 'ce-3',
    title: 'Senior Citizen Help Network',
    type: 'volunteer',
    wardId: 'ward-2',
    lat: 28.652,
    lng: 77.191,
    startsAt: '2026-09-18T10:00:00+05:30',
    slots: 20,
    enrolled: 5,
  },
];

export const SEED_TRANSPARENCY: TransparencyProject[] = [
  {
    id: 'tp-1',
    title: 'Road resurfacing — MG Road stretch',
    wardId: 'ward-1',
    budgetInr: 4500000,
    status: 'ongoing',
    completionPercent: 65,
    summary: 'Resurfacing 1.2 km including drainage gratings.',
  },
  {
    id: 'tp-2',
    title: 'LED streetlight upgrade — Ward 2',
    wardId: 'ward-2',
    budgetInr: 1200000,
    status: 'planned',
    completionPercent: 0,
    summary: 'Replace 400 fixtures with smart dimmable LEDs.',
  },
  {
    id: 'tp-3',
    title: 'Community park — Saket Block C',
    wardId: 'ward-3',
    budgetInr: 800000,
    status: 'completed',
    completionPercent: 100,
    summary: 'Play equipment, walking track, and rainwater harvesting.',
  },
];

export const SEED_DROP_POINTS: WasteDropPoint[] = [
  {
    id: 'wd-1',
    name: 'Segregated Bin — Civil Lines Market',
    type: 'bin',
    lat: 28.6142,
    lng: 77.2095,
    wardId: 'ward-1',
    accepts: ['wet', 'dry'],
  },
  {
    id: 'wd-2',
    name: 'E-Waste Collection — Karol Bagh',
    type: 'ewaste',
    lat: 28.6515,
    lng: 77.191,
    wardId: 'ward-2',
    accepts: ['phones', 'batteries', 'appliances'],
  },
  {
    id: 'wd-3',
    name: 'Recycling Center — Saket',
    type: 'recycling',
    lat: 28.524,
    lng: 77.2065,
    wardId: 'ward-3',
    accepts: ['paper', 'plastic', 'metal'],
  },
];
